services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: [ "node", "start" ]
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
